users:
  - name: ivan
    config:
      bot_token: 1846245302:AAF62xZlF4260iTlPrnHy812OFXmNu0Iwlo
      chat_id: 490087773
      onliner_params:
        - rent_type[]: 2_rooms
        - rent_type[]: 3_rooms
        - price[min]: 250
        - price[max]: 450
        - currency: usd
        - metro[]: red_line
        - metro[]: blue_line
        - bounds[lb][lat]: 53.62870756249745
        - bounds[lb][long]: 27.14187910023304
        - bounds[rt][lat]: 54.050871244278255
        - bounds[rt][long]: 27.83951093617054
        - page: 1
        - order: last_time_up:desc
      realt_params:
        url: https://realt.by/rent/flat-for-long/?search=eJx9T8sOgjAQ%2FJpybnmE9uBB5D82pV2UCJS0VeHvhSpKTPAymZ3ZneyM0KO00KG3hmQFkqw8sMibRw%2B97OaxaJvros6MLiYpKRGnBQsesCQlI5wFfoysMZ17B60ncTTYRi1Z55AfZ%2FSjtEFJZ2UELScHptXrH3kEDv1tmGfpFGh0apPK9lz24zpjPVTT5lRLj2Dx3rjG9DuL7M%2BiRQUDWhjkq1BCv94lNIxR5aLmqKXgcUVFjSrNEmRU0KRO%2BBO%2BU3DU