users:
  - name: ivan
    config:
      bot_token: 1846245302:AAF62xZlF4260iTlPrnHy812OFXmNu0Iwlo
      chat_id: 490087773
      onliner_params:
        - rent_type[]: 2_rooms
        - price[min]: 250
        - price[max]: 400
        - currency: usd
        - metro[]: blue_line
        - bounds[lb][lat]: 53.62870756249745
        - bounds[lb][long]: 27.14187910023304
        - bounds[rt][lat]: 54.050871244278255
        - bounds[rt][long]: 27.83951093617054
        - page: 1
        - order: last_time_up:desc
